### ISSUE TITLE
Messed up my DB when upgrading

### ISSUE THREAD

**Issue by thomasbergmann** [salopensource/sal#11]
Hi Graham,

I´m stuck... tried to upgrade to the new sal repo and messed up the database:

(sal_env)saluser@macsvc:/usr/local/sal_env/sal$ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: sal, staticfiles, admindocs, messages, server, api, bootstrap3
  Apply all migrations: admin, contenttypes, sites, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Creating table server_salsetting
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(_args, *_options)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 309, in sync_apps
    editor.create_model(model)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in **exit**
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'name' used in key specification without a key length")

**Comment by grahamgilbert** [comment]
Damn mysql. Recommend rolling back to your backup. I've had enough of ancient DB tech, I'm going to write a guide on moving over to Postgres (which doesn't have any of the dumb limitations of MySQL.

**Comment by grahamgilbert** [comment]
In all seriousness, I'll see what I can do. But you will need to get back to a working DB by restoring your backup.

**Comment by thomasbergmann** [comment]
Thanks, restore is running. damn it...

**Comment by grahamgilbert** [comment]
This _should_ be fixed now.

**Comment by thomasbergmann** [comment]
I´ll give it a try.

**Comment by grahamgilbert** [comment]
Going to close this. Let me know if you still need help.

**Comment by iamsmaiti** [comment]
Can you just help me with this error: I mean how to solve this//

django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'name' used in key specification without a key length")

**Comment by grahamgilbert** [comment]
On what version? With what database? Postgres is the only officially supported option.
