### ISSUE TITLE
Usage Data Connection Error

### ISSUE THREAD

**Issue by clburlison** [salopensource/sal#124]
I think this is a legit bug in regards to submitting usage data? I've disabled submitting usage data for now to see if that solves my crash.

https://github.com/salopensource/sal/blob/a7d370c0b2bcd4c13af99fb21f0c7270bc559580/server/utils.py#L127-L131

Stack-trace below:

```bash
[28/Jun/2017 12:03:17] ERROR [django.request:124] Internal Server Error: /checkin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/docker/sal/sal/decorators.py", line 119, in wrap
    return function(request, *args, **kwargs)
  File "/home/docker/sal/server/views.py", line 2238, in checkin
    utils.get_version_number()
  File "/home/docker/sal/server/utils.py", line 124, in get_version_number
    version = send_report()
  File "/home/docker/sal/server/utils.py", line 230, in send_report
    r = requests.post('https://version.salopensource.com', data = {"data":post_data})
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))
```

**Comment by grahamgilbert** [comment]
This should definitely be more resilient. In the mean time, I’ll fix the collection server ;)
