### ISSUE TITLE
local variable 'html' referenced before assignment

### ISSUE THREAD

**Issue by fuzzycheck** [salopensource/sal#160]
Hi,

 I'm using Sal 3.2.6.
 I'm seeing this error in the logs.

```
# less sal.log 
[30/Nov/2017 07:15:51] ERROR [django.request:124] Internal Server Error: /pluginload/NetworkCheck/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/docker/sal/server/views.py", line 526, in plugin_load
    return HttpResponse(html)
UnboundLocalError: local variable 'html' referenced before assignment
```

Regards,
Fuzzycheck

**Comment by grahamgilbert** [comment]
This is a problem with a plugin called “NetworkCheck” that as far as I can see isn’t included with either my extra plugin pack or the included ones. Where did you get it from?

**Comment by fuzzycheck** [comment]
The stack trace says there is a problem with a variable called "html" in file "/home/docker/sal/server/views.py", line 526.

```
    return HttpResponse(html)
```

The error happens because the "html" variable is assigned for the first time in a "for" loop, on line 524.

```
html = plugin.plugin_object.widget_content(page, machines, theID)
```

The error would go away if you defined the "html" variable outside the "for" loop, for example on line 520, for example with an empty string.

```
html = ""
```

More info on this python error:
https://stackoverflow.com/questions/15367760/unboundlocalerror-local-variable-referenced-before-assignment-when-reading-from

**Comment by grahamgilbert** [comment]
I understand this, but the problem was caused by a malfunctioning plugin. I would rather not mask these issues.

**Comment by fuzzycheck** [comment]
sorry, my docker server died, so I'm not able to test right now.
Was I saw before it died is that there is no sign in the web interface that a plugin died, and also the plugin doesn't appear in the settings, so I couldn't disable it.

my idea is to test something like

```
html = """
    <div class="panel panel-default panel-traffic-light">
        <div class="panel-heading">
            Plugin Error
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          Please check the logs for "Internal Server Error: /pluginload/xxx"
        </div>
      </div>
"""
```
