### ISSUE TITLE
Plugins Page Errors on 3.3.4

### ISSUE THREAD

**Issue by Zolotkey** [salopensource/sal#246]
The Plugin Page Errors out with old plugins installed. 

Here is the Traceback:

```
[26/Apr/2018 11:25:47] ERROR [django.request:124] Internal Server Error: /settings/plugins/
Traceback (most recent call last):
  File "/usr/local/laika/sal/sal_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/laika/sal/sal_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/laika/sal/sal_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/laika/sal/sal_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/laika/sal/sal_env/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/laika/sal/sal/decorators.py", line 228, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/laika/sal/server/settings_views.py", line 210, in plugins_page
    context = {'plugins': utils.get_active_and_inactive_plugins('machines')}
  File "/usr/local/laika/sal/server/utils.py", line 525, in get_active_and_inactive_plugins
    elif DEPRECATED_PLUGIN_TYPES[plugin.get_plugin_type()] != plugin_type:
KeyError: 'condition'
```

**Comment by Zolotkey** [comment]
It must have, FYI I removed Grahams old plugins and issue went away...

**Comment by Zolotkey** [comment]
https://github.com/salopensource/grahamgilbert-plugins/blob/master/oncorp/oncorp.py#L12
