### ISSUE TITLE
`server_maintenance` exception on v4 managed_items branch

### ISSUE THREAD

**Issue by weswhet** [salopensource/sal#316]
Just tracking any issues I see testing the latest and greatest.

running `python manage.py server_maintenance` on the `managed_items_feature` branch throws the following exception.

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/docker/sal/server/management/commands/server_maintenance.py", line 36, in handle
    ManagedItemHistory.objects.filter(recorded__lt=datelimit).delete()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 663, in delete
    deleted, _rows_count = collector.delete()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/deletion.py", line 282, in delete
    count = qs._raw_delete(using=self.using)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 677, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/subqueries.py", line 75, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "server_manageditemhistory" does not exist
LINE 1: DELETE FROM "server_manageditemhistory" WHERE "server_manage...
```

**Comment by sheagcraig** [comment]
Let me know if we can close this @weswhet

**Comment by weswhet** [comment]
Yeah, pretty sure this was from a bad DB migration on my test box. I'll reopen if I notice it again.
