### ISSUE TITLE
Error running " python manage.py migrate"

### ISSUE THREAD

**Issue by tpegues2** [salopensource/sal#347]
Running sal 3.3.16 with python 3.6 on RHEL7.
When I attempt to run "python manage.py migrate".
The database already has data in it as I am attempting to simply upgrade my version of python as part of a migration to sal 4.0 where python will need to be upgrade. 
I had to create a new virtual env with the new version of python and thus download sal 3.3.16 in the new virtual env and follow the same steps.   I'm not sure I followed the #216 solution. Does it apply here?  

===============================================

(sal_env) [saluser@devrhel7 sal]$ python ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/saluser/sal_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/saluser/sal_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/srv/saluser/sal_env/lib/python3.6/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/srv/saluser/sal_env/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/srv/saluser/sal_env/lib/python3.6/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/srv/saluser/sal_env/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/saluser/sal_env/sal/sal/settings.py", line 2, in <module>
    from system_settings import *
ModuleNotFoundError: No module named 'system_settings'

**Comment by grahamgilbert** [comment]
Your settings file is out of date. Start again from the one included with Sal 4.

**Comment by tpegues2** [comment]
First of all, thanks!!!!  I wanted to get python3.6 working with Sal 3.3.16 initially because we have other applications that are effected by the newer versions of software we will need to install to support Sal 4.0.  We are doing it in stages. The first stage was to update postgres which has been done. The second step was to upgrade python to a supported version and once we were done with all the supporting software (postgres, python, Django) tackle Sal 4.0.  Can we use the settings file from Sal 4.0 with the 3.3.16?  Just for clarity.

**Comment by grahamgilbert** [comment]
It’s highly unlikely that it will work without modification. The maintainers have never done that before.

**Comment by tpegues2** [comment]
Ok, then I will need to stay with the 3.3.16 settings file?
Any recommendations as to what to try next to get rid of the errors I’m getting using python36?
I take it python36 is supported with the Sal 3.3.16 version?

**Comment by grahamgilbert** [comment]
No, python 3 is not supported on Sal 3. Either downgrade to python 2, upgrade to Sal 4 or use the supported deployment method (docker).

**Comment by tpegues2** [comment]
Graham I got it working with Sal 4.0.3 and Python 3 but I've noticed there is no "sal.log" being generated. Is this something I need to configure?  It's always just shown up before.  We are not using Docker but I see the code in Docker that would normally put it in place.  I did create the sal.log file but it receives no output.

**Comment by grahamgilbert** [comment]
@sheagcraig - logging just goes to stdout / stderr now, right?
