### ISSUE TITLE
manage.py syntaxerror after update

### ISSUE THREAD

**Issue by tlehtil** [salopensource/sal#349]
I tried to update sal to 4.0.3 version, but when running the python manage.py migrate it gives following error:
(sal_env) $ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/sal_install/sal_env/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/sal_install/sal_env/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/sal_install/sal_env/local/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/sal_install/sal_env/local/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/sal_install/sal_env/local/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/sal_install/sal_env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/sal_install/sal/server/models.py", line 345
    f"{self.machine}: {self.management_source.name} {self.name} {self.status} "
                                                                                                                              ^
SyntaxError: invalid syntax

Server version: 
Ubuntu 16.04
python version:
Python 3.5.2
Database: 
Postgresql
Version: 9.5+173ubuntu0.2

**Comment by sheagcraig** [comment]
Python f strings require at least python version 3.6. The recommended Docker version uses Python 3.7.1, for example. The maintainers all use the Docker image, so the non-Docker documentation is probably in need of update if anyone wants to contribute to that.
