### ISSUE TITLE
Support different date formats than US

### ISSUE THREAD

**Issue by jby** [salopensource/sal#351]
**Describe the bug**
sal-submit complains about unrecognized date format when using something else than US date format

**To Reproduce**
Use a different timezone than any US-timezone
Try to manuallly submit data to sal, using sal-submit

**Expected behavior**
Return of prompt, data populated in sal server.

**Server (please complete the following information):**
 - Host environment Docker on RHEL 7
 - Version 4.0.3 (really 4.x)

**Client (please complete the following information):**
 - OS: [macOS]

**Additional context**
Output from sal-submit command:

```
sudo /usr/local/sal/bin/sal-submit -v                                                                                           2019-11-01 19:49:37,065 INFO sal-submit Version: 3.0.0
2019-11-01 19:49:38,175 INFO Processing checkin modules...
Traceback (most recent call last):
  File "/usr/local/sal/checkin_modules/apple_sus_checkin.py", line 188, in <module>
    main()
  File "/usr/local/sal/checkin_modules/apple_sus_checkin.py", line 19, in main
    sus_report = get_sus_install_report()
  File "/usr/local/sal/checkin_modules/apple_sus_checkin.py", line 93, in get_sus_install_report
    installed = datetime.datetime.strptime(line[-1], '%m/%d/%Y, %H:%M:%S')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2019-10-30, 18:43:41' does not match format '%m/%d/%Y, %H:%M:%S'
2019-11-01 19:49:39,913 INFO Processing plugins...
2019-11-01 19:49:43,822 INFO Processing inventory...
2019-11-01 19:49:44,321 INFO Inventory is out of date; submitting...
2019-11-01 19:49:45,773 INFO Processing catalogs...
2019-11-01 19:49:45,903 INFO Processing profiles...
2019-11-01 19:49:46,219 INFO Checkin complete.
```

If possible, please replicate the issue while Sal is in [debug mode](https://github.com/salopensource/sal/wiki/Troubleshooting).
N/A

scripts version:
```
package-id: com.github.salopensource.sal_scripts
version: 3.0.0
```

**Comment by jby** [comment]
This should have been against the sal-scripts repo and not here.
Created https://github.com/salopensource/sal-scripts/issues/63 instead.
