### ISSUE TITLE
Unable to get to a single client host

### ISSUE THREAD

**Issue by jby** [salopensource/sal#369]
**Describe the bug**
When trying to view a single client I get this:
![image](https://user-images.githubusercontent.com/1584888/73071293-b5000680-3eb2-11ea-977f-ab2875b38238.png)

**To Reproduce**
1. Go to the page of a single client (http://host.domain.tld/machine_detail/61/

**Expected behavior**

**Screenshots**
See above
**Server (please complete the following information):**
Docker in CentOS, Sal version 4.0.3.2046 (from macadmins/sal)

**Client (please complete the following information):**
 - OS: macOS 10.15.2
 - Browser Safari (13.0.4), Firefox (72.0.2) or Chrome (79.0.3945.130)

**Additional context**
Log:
```
==> salmain-stderr---supervisor-WyoBvo.log <==
[24/Jan/2020 11:27:06] ERROR [django.request:228] Internal Server Error: /machine_detail/61/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/docker/sal/sal/decorators.py", line 113, in wrapper
    return function(*args, **kwargs)
  File "/home/docker/sal/server/views.py", line 337, in machine_detail
    output = utils.get_machine_detail_placeholder_markup(machine)
  File "/home/docker/sal/server/utils.py", line 643, in get_machine_detail_placeholder_markup
    manager = PluginManager()
  File "/home/docker/sal/sal/plugin.py", line 398, in __init__
    "Singleton can't be created twice! Client code should use classmethods to retrieve"
Exception: Singleton can't be created twice! Client code should use classmethods to retrieve an instance!
```

**Comment by sheagcraig** [comment]
This is strange; I'm not sure how I missed this. The error is correct. The utils.get_machine_detail_placeholder_markup func is trying to instantiate a faux-singleton and this exception is raised to say hey! What are you doing!

I can fix this pretty quickly. I'm just wondering if it's already been fixed in a branch sitting around somewhere that hasn't been merged.

**Comment by jby** [comment]
The original issue is solved, but I'm now getting the same error (in my browser) one step deeper into the app. I can select a single client, click on "Application Inventory" and when I then try to find  info about a (any) application on that client I get the same browser error.
I'll try to capture the logs for it as well.

**Comment by jby** [comment]
And logs:

```
cat salmain-stderr---supervisor-AJfsbY.log
[04/Mar/2020 09:03:03] ERROR [django.request:228] Internal Server Error: /inventory/list/machine/1/106/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/docker/sal/sal/decorators.py", line 70, in decorator
    return function(*args, **kwargs)
  File "/home/docker/sal/datatableview/views/base.py", line 25, in dispatch
    return super(DatatableJSONResponseMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "/home/docker/sal/inventory/views.py", line 230, in get_queryset
    queryset = self.filter_queryset_by_group(self.model.objects.all())
  File "/home/docker/sal/inventory/views.py", line 143, in filter_queryset_by_group
    queryset = queryset.filter(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1189, in build_filter
    raise FieldError("Cannot parse keyword query %r" % arg)
django.core.exceptions.FieldError: Cannot parse keyword query ''
```
