### ISSUE TITLE
ImportError when building on Heroku

### ISSUE THREAD

**Issue by kcrawshaw** [salopensource/sal#4]
I followed along with the instructions for how to deploy Sal on Heroku. https://github.com/salopensource/sal/blob/master/docs/Deploying_on_Heroku.md

When I run `heroku run python manage.py syncdb` I get an import error because the settings module cannot be found? Not sure if the sal directory needs to be in the system path. Any help or suggestions for a fix would be appreciated.

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named settings
```

**Comment by grahamgilbert** [comment]
Is settings.py in the .gitignore file? It needs to be taken out (I should update those instructions I guess you can tell how often I use Heroku...). 

Graham Gilbert

**Comment by kcrawshaw** [comment]
It certainly was in the .gitignore file. Didn't even think to check there! I am receiving a new error though...

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/app/sal/settings.py", line 2, in <module>
    from system_settings import *
  File "/app/sal/system_settings.py", line 220, in <module>
    DATABASES['default'] =  dj_database_url.config()
NameError: name 'DATABASES' is not defined
```

**Comment by Ubertec** [comment]
I get the same error also when trying to build with heroku on OS X. It looks like the line: "cp sal/example_settings.py sal/settings.py' is incorrect & should be "cp sal/system_settings.py sal/settings.py" im testing now.

**Comment by chasetb** [comment]
If you do that, make sure you include the "DATABASE" section from example_settings.py in your new settings.py or Sal won't know where your database is.

**Comment by Ubertec** [comment]
good point

**Comment by Ubertec** [comment]
However does not help, still fails with the same DATABASES error.

**Comment by grahamgilbert** [comment]
Please don't overwrite system_settings.py - bad things will happen.

It looks like Heroku have changed a lot on their end - I don't use it, and
it's expensive to use for any reasonably sized installation, so following a
kind offer from Thomas Dam to write some beginner documentation for getting
running on Digital Ocean (which is using Docker, so therefore heavily
tested and used in production by many people), I'm going to deprecate
running on Heroku. If someone wants to work out how to fix things, then
please do, but otherwise the recommended path to running Sal outside of
your own data centre will be in DO.

**Comment by RIPLIK** [comment]
help me )!

Traceback (most recent call last):
  File "botomatic.py", line 10, in <module>
    import settings
ImportError: No module named settings

**Comment by Ubertec** [comment]
Hi salopensource/sal

We just got your message, thanks for writing in! We’ll get back
to you with a response as quickly as possible. We are open
Wednesday-Friday (9am-5:30pm) we do our best to reply within a
couple of hours. Evenings and weekends might take a little bit
longer.

Cheers,

Tony,

Übertec. Apple Authorised Service Provider

www.ubertec.co.nz ( http://www.ubertec.co.nz ) 3 St Georges Bay
Road, Parnell 
( http://maps.apple.com/?lsp=9902&auid=12984604227473377904&sll=-36.858146,174.782817&q=Ubertec&hnear=-36.858146,174.782817 )


[+649].358.3801 ( tel:+6493583801 ) | Twitter 
( http://twitter.com/ubertec ) | FaceBook 
( http://facebook.com/ubertec ) | Newsletter 
( http://ubertec.co.nz/promotions/newsletter )

Ubertec Logo ( www.ubertec.nz )

**Comment by grahamgilbert** [comment]
In the absence of anyone volunteering documentation, running in heroku isn’t supported. I haven’t used it for years and no one has taken up the documentation mantle. If anyone wants to volunteer to take on documenting its use, we can revisit this.
