### ISSUE TITLE
ERROR [django.request:228] Internal Server Error: /checkin/

### ISSUE THREAD

**Issue by tpegues2** [salopensource/sal#416]
We've been getting Internal Server Errors in my /var/log/messages in my Linux 8 environment.  

**To Reproduce**
It seems to occur as machines check into the environment but it doesn't happen for all the machines that do the checkin but only certain ones as the error occurs randomly.

**Expected behavior**
I would expect that these errors would not appear as they have not occurred in the past.

**Screenshots**
Feb 14 03:17:58 onemorething gunicorn: [14/Feb/2021 03:17:58] ERROR [django.request:228] Internal Server Error: /checkin/
Feb 14 03:17:58 onemorething gunicorn: Traceback (most recent call last):
Feb 14 03:17:58 onemorething gunicorn: File "/srv/saluser/sal_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
Feb 14 03:17:58 onemorething gunicorn: response = get_response(request)
Feb 14 03:17:58 onemorething gunicorn: File "/srv/saluser/sal_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
Feb 14 03:17:58 onemorething gunicorn: response = self.process_exception_by_middleware(e, request)
Feb 14 03:17:58 onemorething gunicorn: File "/srv/saluser/sal_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
Feb 14 03:17:58 onemorething gunicorn: response = wrapped_callback(request, *callback_args, **callback_kwargs)
Feb 14 03:17:58 onemorething gunicorn: File "/srv/saluser/sal_env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Feb 14 03:17:58 onemorething gunicorn: return view_func(*args, **kwargs)
Feb 14 03:17:58 onemorething gunicorn: File "/srv/saluser/sal_env/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
Feb 14 03:17:58 onemorething gunicorn: return func(request, *args, **kwargs)
Feb 14 03:17:58 onemorething gunicorn: File "/srv/saluser/sal_env/sal/sal/decorators.py", line 169, in wrap
Feb 14 03:17:58 onemorething gunicorn: return function(request, *args, **kwargs)
Feb 14 03:17:58 onemorething gunicorn: File "/srv/saluser/sal_env/sal/server/non_ui_views.py", line 283, in checkin
Feb 14 03:17:58 onemorething gunicorn: MachineGroup, key=submission["Sal"]["extra_data"].get("key")
Feb 14 03:17:58 onemorething gunicorn: KeyError: 'Sal'

**Server (please complete the following information):**
 - Host environment [Linux]
 - Version [Sal 4.1.9]

**Client (please complete the following information):**
 - OS: [Linux 8]
 - Browser [safari]

**Additional context**

If possible, please replicate the issue while Sal is in [debug mode](https://github.com/salopensource/sal/wiki/Troubleshooting).
Only happens in our production environment but not in our test environment.

**Comment by grahamgilbert** [comment]
Are your clients running an out of date client scripts version?

**Comment by tpegues2** [comment]
I will validate with the client team and let you know.

**Comment by tpegues2** [comment]
There some clients that are out of date but the latest version is installed once they check in.
Could this be what I am seeing in the error logs?

**Comment by grahamgilbert** [comment]
Yes, that would be my guess.

**Comment by grahamgilbert** [comment]
Closing due to inactivity.
