### ISSUE TITLE
Can't create Machine Group with API

### ISSUE THREAD

**Issue by sheagcraig** [salopensource/sal#81]
Perhaps I'm doing this wrong...

```
import requests
import json

data = json.dumps({"business_unit": 1, "name": "PartyHaus"})
response = requests.post("https://sal.is.the.bomb.com/api/machine_groups", headers={"privatekey": "something", "publickey": "also_something"}, data=data)
```

results in response 500 and the following in the server logs:

```
[12/Dec/2016 15:46:36] ERROR [django.request:124] Internal Server Error: /api/machine_groups/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/docker/sal/api/auth.py", line 14, in wrap
    return function(request, *args, **kwargs)
  File "/home/docker/sal/api/views.py", line 204, in machine_group_list
    serializer.save()
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 192, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 890, in create
    raise TypeError(msg)
TypeError: Got a `TypeError` when calling `MachineGroup.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `MachineGroup.objects.create()`. You may need to make the field read-only, or override the MachineGroupSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 873, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
TypeError: save() got an unexpected keyword argument 'force_insert'
```

**Comment by grahamgilbert** [comment]
Well that looks problematic. I've not used this since the API was written, so something might have broken...

**Comment by sheagcraig** [comment]
Just to be sure, I tested adding Business Units with the API-that seems to work. I'll update the wiki to give an example of POST data, since it may not be clear from the wiki what is needed to constitute a POST request.

**Comment by sheagcraig** [comment]
Also, it's not explicitly mentioned in the wiki, but to POST, you need a trailing slash on the URL (unless my Sal is strangely configured)

`RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to sal.yes.com/api/machine_groups/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.`

**Comment by grahamgilbert** [comment]
This will be fixed in the next release.
